# Generated by Django 4.2.3 on 2023-09-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioproject',
            name='screenshoot',
            field=models.ImageField(upload_to='images/projects/'),
        ),
    ]
