# Generated by Django 4.2.3 on 2023-09-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectreview',
            name='reviews',
            field=models.CharField(max_length=200),
        ),
    ]
