# Generated by Django 4.2.3 on 2023-09-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projectreview_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectreview',
            name='ratings',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
    ]
